### ISSUE TITLE
SDL: Disables screensaver

### ISSUE THREAD

**Issue by JasonInOttawa** [koreader/koreader-base#1090]
SDL 2.0 defaults to "disable screensaver", so leaving the emulator running keeps the screensaver from starting (at least it does on a Mac).

The attached files call SDL_EnableScreensaver to fix this.

[SDL2_0.lua.txt](https://github.com/koreader/koreader-base/files/4541553/SDL2_0.lua.txt)
[SDL2_0_h.lua.txt](https://github.com/koreader/koreader-base/files/4541554/SDL2_0_h.lua.txt)

**Comment by magicmirror1365** [comment]
pmset -g assertions

   pid 56400(luajit): [0x0001681a00059f9b] 00:00:06 PreventUserIdleDisplaySleep named: "luajit using SDL_DisableScreenSaver"

**Comment by magicmirror1365** [comment]
Alternatively setting this environment variable enables the screensaver

export SDL_VIDEO_ALLOW_SCREENSAVER=1

**Comment by Frenzie** [comment]
Thanks, sounds good. You don't want to put it in a PR? :-)

**Comment by magicmirror1365** [comment]
Thanks, I will do that.

Would adding the environment variable to the kodev script be a good way to proceed?

**Comment by Frenzie** [comment]
What you've proposed here seems better to me, applicable to all (SDL) platforms in all conditions.

**Comment by magicmirror1365** [comment]
Thanks again. Would adding it to the kodev script also propagate the change to the Linux deb/rpm?

(I'm not sure how much of this works)

**Comment by JasonInOttawa** [comment]
Sorry, I misunderstood. I will put the code changes to the SDL lua files in a PR

**Comment by JasonInOttawa** [comment]
The change is in PR 1091
