### ISSUE TITLE
czmq: kindle build fails

### ISSUE THREAD

**Issue by yparitcher** [koreader/koreader-base#1120]
```
koreader/base/thirdparty/czmq/build/arm-kindlepw2-linux-gnueabi/czmq-prefix/src/czmq/src/../include/czmq_prelude.h:518:17: fatal error: uuid/uuid.h: No such file or directory
 #       include <uuid/uuid.h>
```

it thinks i have uuid available (I think autotools catches the system install).

this works fine building the emulator as the system libraries are actually available.

This is my reward for running `kodev clean` by mistake :)

**Comment by yparitcher** [comment]
commenting out:
 koreader/base/thirdparty/czmq/build/arm-kindlepw2-linux-gnueabi/czmq-prefix/src/czmq-build/src/platform.h

```
#define HAVE_LIBUUID 1
```

was a quick and dirty way to let it succeed

**Comment by NiLuJe** [comment]
The configure script should never have picked up LIBUUID in the first place, it's part of `util-linux`, which we don't build...

**Comment by NiLuJe** [comment]
Then again, that's a 7 years old czmq snapshot, so, who knows...

**Comment by NiLuJe** [comment]
I have a mild hunch that a clean checkout would work just fine ^^.

**Comment by yparitcher** [comment]
This was my problem ;)

I was building a different program that needed to be linked against the kindle's `lipc` so i copied `lipc` and dependecies from my kindle into my TC sysroot. this included `libuuid.so`. deleting it solved the issue.

this that our `czmq` is 8 years old didn't help anything, so i can't even disable `uuid` as a config option.

**Comment by Frenzie** [comment]
Updating that zmq stuff is slightly non-trivial and nobody's motivated to put in the time. ;-)
