### ISSUE TITLE
Is it doable/reasonable to add opencv?

### ISSUE THREAD

**Issue by Galunid** [koreader/koreader-base#1148]
I was thinking about writing a module that would allow users to double tap a panel in manga to zoom to a selected panel(basically cut out part of the image and display it).
**Base image:**
![image1](https://user-images.githubusercontent.com/10298730/88061322-a6e02980-cb67-11ea-9b89-e774dc75fc4d.png)
**Cut out panels:**
![image4](https://user-images.githubusercontent.com/10298730/88061334-a8a9ed00-cb67-11ea-8c66-eafa83c8effc.png)
![image3](https://user-images.githubusercontent.com/10298730/88061331-a8a9ed00-cb67-11ea-9482-bbb3e9bedbf4.png)
![image2](https://user-images.githubusercontent.com/10298730/88061327-a8115680-cb67-11ea-8165-b98fef40f1a7.png)

To get this result I used opencv library and a short python script https://pastebin.com/hKKGgzNw. My question is whether it's reasonable to include OpenCV, and if so, how would I go around it?

**Comment by Frenzie** [comment]
OpenCV seems like it might be rather excessively large for our purposes, even setting aside some potential doubts about its usability on a poor little Kindle or Kobo.

But perhaps more important, Leptonica should mostly likely do the same thing faster and we already have it. In fact I implicitly mentioned it in https://github.com/koreader/koreader/pull/6408#issuecomment-661877691 although I didn't speak of some of the underlying technology. In fact the current zoom in page flipping mode already functions roughly the way you sketched. ;-)

Some examples:
https://github.com/koreader/koreader-base/blob/0e6406696f233d4f7033803bcd38e4b7559e7e40/ffi/koptcontext.lua#L232-L258

https://github.com/koreader/koreader-base/blob/0e6406696f233d4f7033803bcd38e4b7559e7e40/ffi/koptcontext.lua#L260-L335

Clearly the fact that it's hidden in page flipping mode means almost no one knows it exists. So there are multiple issues. 

* The zoom to box feature is great *as a starting point* and it's neat most of the time but it doesn't always work out. You want much freer zoom.
  Some details on things we might want in free zoom here: https://github.com/koreader/koreader/issues/5524
* Ideally all this would somehow be available in the main reader mode easily without having to trigger a mostly hidden special mode.
  I'm not sure page flipping mode still has much purpose with the greatly improved skim widget.

**Comment by NiLuJe** [comment]
basically what @Frenzie said ;).

(OpenCV is humongous, and I don't think it has any arm-specific codepaths).

**Comment by Galunid** [comment]
Just like I thought. I'll take a look at leptonica, but to be fair, there doesn't seem to be a lot of resources to learn from, so I'll probably give it up.
