### ISSUE TITLE
Are those two lines necessary?

### ISSUE THREAD

**Issue by zwim** [koreader/koreader-base#1285]
https://github.com/koreader/koreader-base/blob/22d3b504d43e058a0d06c585fda8459749de0c3e/cre.cpp#L3163-L3164

I have commented them out and noticed no rendering differences when changing rotating, font size, hanging punctuation, status bars ...
I seems that the document gets rendered before calling `drawCurrentPage`.

**Comment by poire-z** [comment]
May be with the way we use crengine, they could be not needed, dunno.
But these are mostly no-op when things hasn't changed, so best to not take any risk :) 

The way crengine works is that when we change stuff (width/height, font size, css...), we just set properties (and that's what this Resize(w,h) does) - and it's just later when drawing a page that it checks if any property has changed (this Render()), with various direct comparisons, and computing various kind of hashes from some other properties and styles - and if anything has changed, it does a real re-rendering (this step that sometimes take a few seconds).

So, there, we're just making crengine checks that it's cached rendering is in-sync with the settings and the view w/h. If the quick checks say all is good, not much is done and page can be drawn.

**Comment by zwim** [comment]
OK, I understand: Better safe than sorry.
