### ISSUE TITLE
button-listen doesn't seem to work on reMarkable 1

### ISSUE THREAD

**Issue by klapaukh** [koreader/koreader-base#1426]
On the reMarkable 1 middle button launching of koreader seems to have stopped working. It appears to be linked to button-listen not working. Manually running "systemctl start koreader" works, but manually running button-listen and long-pressing buttons doesn't work.

(Tested on koreader v2021.10, and xochitl 2.10.0.324)

There is more detail at, though it seems like it might be the wrong project: https://github.com/koreader/koreader/issues/8242

**Comment by pazos** [comment]
Yup. A fw update broke things.

There's no active developer with a ReMarkable here, so we can't fix anything. Patches very welcome (or an alternate way of launching the program, there are plenty, written to the wiki/install instructions).

**Comment by klapaukh** [comment]
I had a play around with modifying  `button-listen.c` on a RM1 post firmware update and it seems that `/dev/input/event2` now returns touch input events, but not button presses. In contrast, `/dev/input/event1` seems to have the button presses, but not touch events.
I guess in order to support both options it would need to read from both files, so it could work on pre/post update devices.

**Comment by klapaukh** [comment]
I've created a PR with a fix that works on my post update rM1 device (and I think should work on the others, as it preserves the old behaviour).
