### ISSUE TITLE
lunasvg compile error with gcc-13.1.0

### ISSUE THREAD

**Issue by zwim** [koreader/koreader-base#1604]
lunasvg does not compile with gcc 13.1.0

[compile.log.txt](https://github.com/koreader/koreader-base/files/11365891/compile.log.txt)

**Comment by poire-z** [comment]
`export LANG=C` before compiling if you want me to understand the compiler error message :) and get better help from Google when pasting them.

**Comment by NiLuJe** [comment]
The first bit looks like its simply missing a `<cstdint>` include (which makes sense, that's where <stdint.h> is in C++ ;o).

**Comment by yparitcher** [comment]
> The first bit looks like its simply missing a `<cstdint>` include (which makes sense, that's where <stdint.h> is in C++ ;o).

:+1: 
This is fixed on lunasvg master, I tried bumping it, but the patch does not apply cleanly.
@poire-z 
Can you take a look

**Comment by benoit-pierre** [comment]
You need this patch:
```diff
diff --git a/include/lunasvg.h b/include/lunasvg.h
index 5f293f59..abc64799 100644
--- a/include/lunasvg.h
+++ b/include/lunasvg.h
@@ -26,6 +26,7 @@
 #include "xlunasvg.h"
 #include <memory>
 #include <string>
+#include <cstdint>
 
 #if defined(_MSC_VER) && defined(LUNASVG_SHARED)
 #ifdef LUNASVG_EXPORT
diff --git a/source/property.h b/source/property.h
index 0fa3895f..82cdd09f 100644
--- a/source/property.h
+++ b/source/property.h
@@ -4,6 +4,7 @@
 #include <vector>
 #include <string>
 #include <array>
+#include <cstdint>
 
 namespace lunasvg {
 
```

**Comment by poire-z** [comment]
^ bumped (rather than an addtional patch on our side).

**Comment by Frenzie** [comment]
Usually better. ;-)
