### ISSUE TITLE
Gentoo zlib mirror link no longer available

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader-base#1654]
Should we switch back to <http://zlib.net/fossils/>? Cf. https://github.com/koreader/koreader-base/pull/840

Incidentally, 1.3 has been out since a few weeks ago, but I don't feel like investigating those patches. ;-)

Edit: these days they also have it up on <https://github.com/madler/zlib/releases/download/v1.2.13/zlib-1.2.13.tar.xz>, the official GH repo. With any luck that's a dependable solution.

**Comment by ryanwwest** [comment]
I picked exactly the wrong time to try to start building a dev environment, getting [a 404](https://github.com/koreader/koreader/discussions/10901) from this. Following.

**Comment by Frenzie** [comment]
I'm waiting for @NiLuJe to comment since I don't know all that much about Gentoo or that mirror. But you can just switch the URL to one of the two I mentioned here.

**Comment by NiLuJe** [comment]
That's one of the main US mirrors for Gentoo distfiles, and 1.3 was still masked yesterday, so, strange that it's gone...

In any case, switching to GH probably makes sense, I'll do that :).

**Comment by ryanwwest** [comment]
I'm still getting the 404 error after pulling and restarting the instructions from the beginning... does koreader-base module not get pulled to master by default?

**Comment by NiLuJe** [comment]
Nope, it's pinned to a specific commit. You ought to be able to run a checkout manually, though, I'm not sure anything really screws with that (perhaps make fetchthirdparty).

**Comment by ryanwwest** [comment]
Thanks, I will try manual checkout. On that note, for https://github.com/koreader/koreader/issues/10892 I need to modify to get the PDF ID 'fingerprint'—are there any instructions on how to have `koreader-base` being developed at the same time as `koreader` and both being used to build? At first glance `koreader-base` within `koreader/.git/modules/` seems inaccessible for actual development, just building.

(Needed change is adding in a 3 line wrapper function similar to [this](https://github.com/koreader/koreader-base/blob/f006f9074067f707b7a1bcdd93fa53c6a50620cc/wrap-mupdf.h#L76-L78) -> [this](https://github.com/ArtifexSoftware/mupdf/blob/79465406bd8591ff9a20b0a7e3ee97a3d04fd8b8/source/fitz/document.c#L500-L507), but instead wrapping `pdf_load_object` [here](https://github.com/ArtifexSoftware/mupdf/blob/79465406bd8591ff9a20b0a7e3ee97a3d04fd8b8/source/pdf/pdf-xref.c#L2617-L2622) get the last xref object aka the 'trailer' containing the ID).

**Comment by ryanwwest** [comment]
Hmm, maybe I can just modify koreader-base within `base/` after it's loaded and that'll work.

**Comment by Frenzie** [comment]
Yup, either directly or by switching branches in there.

But note you can also specify a different base folder in some environment variable I can't think of otoh if you want to keep them all open for editing at once or something.
