### ISSUE TITLE
build fails for folder with spaces

### ISSUE THREAD

**Issue by hugleo** [koreader/koreader-base#1672]
mkdir "folder space"
cd folder\ space/
git clone https://github.com/koreader/koreader.git
cd koreader && ./kodev fetch-thirdparty
./kodev build

.....

cd thirdparty/luajit/build/x86_64-pc-linux-gnu-debug && \
        cmake -G Ninja \
        -DCC='/usr/bin/ccache gcc' \
        -DXCOMPILE:BOOL=off \
        -DBASE_CFLAGS='-Og -g -pipe -fno-omit-frame-pointer' \
        -DHOST_CFLAGS='-march=native -Og -g -pipe -fno-omit-frame-pointer ' \
        -DLDFLAGS='-Wl,-O1 -Wl,--as-needed -Wl,@/home/hugleo/Desktop/ space/koreader/base/origin.ldflags '   \
        -DTARGET_SONAME='libluajit.so' \
        -DTARGET_CFLAGS='-Og -g -pipe -fno-omit-frame-pointer   -march=native -fPIC -DLUAJIT_SECURITY_STRHASH=0 -DLUAJIT_SECURITY_STRID=0' \
        -DCROSS='' \
        /home/hugleo/Desktop/folder space/koreader/base/thirdparty/luajit && \
        /usr/bin/ninja 
CMake Warning:
  Ignoring extra path from command line:

   "space/koreader/base/thirdparty/luajit"

CMake Error: The source directory "/home/hugleo/Desktop/folder" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
make[1]: *** [Makefile.third:313: build/x86_64-pc-linux-gnu-debug/luajit] Error 1
make[1]: Leaving directory '/home/hugleo/Desktop/folder space/koreader/base'
make: *** [Makefile:134: base/build/x86_64-pc-linux-gnu-debug/luajit] Error 2
Failed to build emulator! Try run with -v for more information.

**Comment by Frenzie** [comment]
Can't do much about that at least for now but possibly ever. Make doesn't like spaces. See https://www.cmcrossroads.com/article/gnu-make-meets-file-names-spaces-them

**Comment by hugleo** [comment]
Okay,

It uses absolute paths instead of relative paths:

https://github.com/koreader/koreader/blob/9e82761c45115cfcab7d35951fa39b6158d9c6f5/kodev#L13
https://github.com/koreader/koreader-base/blob/350f519d283c6ef3952a091f92d1a3a6899c90ce/Makefile.defs#L17C1-L17C83

And possible in others places. It's not worth escaping everything. Just better to keep folders without spaces.
