### ISSUE TITLE
curl fails to build with autoconf 2.72

### ISSUE THREAD

**Issue by yparitcher** [koreader/koreader-base#1729]
https://github.com/koreader/koreader/pull/11350#issuecomment-1891195704

**Comment by NiLuJe** [comment]
My current plan is to see if throwing an `autoreconf -fi` at it doesn't magically fix it (because, IIRC, updating cURL implies doing nasty things to zsync2 that I don't have time to deal with ;p);

**Comment by yparitcher** [comment]
> My current plan is to see if throwing an `autoreconf -fi` at it doesn't magically fix it (because, IIRC, updating cURL implies doing nasty things to zsync2 that I don't have time to deal with ;p).

It doesn't, buildconf says to run that instead so i tried it and it did not help :(

**Comment by NiLuJe** [comment]
Fixed via #1732 ;).
