### ISSUE TITLE
macOS Github workflow

### ISSUE THREAD

**Issue by benoit-pierre** [koreader/koreader-base#1789]
Just received from Github:

> The macOS 11 runner image will be removed by 6/28/24. To raise awareness of the upcoming removal, jobs using macOS 11 will temporarily fail during scheduled time periods defined below:
>
> June 17 2024, 8:00 AM - 2:00 PM EST
> June 19 2024, 12:00 PM - 6:00 PM EST
> June 24 2024, 3:00 AM - 9:00 PM EST
> June 26 2024, 8:00 AM - 2:00 PM EST
>
> What you need to do
>
> Jobs using the macos-11 YAML workflow label should be updated to macos-14, macos-13, macos-12, or macos-latest. You can always get up-to-date information on our tools by reading about the software in the runner images repository. Please contact GitHub Support if you run into any problems or need help. 

The koreader workflow is already using macos-13, despite this warning in the file:
```yaml 
    # macos-11, macos-12 & macos-13 are broken at this time being.
    # https://github.com/koreader/koreader/issues/8686,
    # https://github.com/koreader/koreader/issues/8686#issuecomment-1172950236

    # Please don't update to newer macOS version unless you can test that the new
    # action produces working binaries.
    # 10.15 is no longer supported so we are running 13 just to make sure the build does not break.
    runs-on: macos-13
```

Since the resulting build seem to work fine once the build system stuff is merged (Cf. [discussion](https://github.com/koreader/koreader/pull/11660#issuecomment-2105360284)), should we update to macos-13? Or is the intent to test another configuration (macos-12)?

**Comment by Frenzie** [comment]
I doubt there's much reason to use an older one.

**Comment by benoit-pierre** [comment]
For the deployment target? From my experience on another project, this determine the oldest supported macos version if you want to distribute the resulting binaries.

**Comment by benoit-pierre** [comment]
Sorry, I though this was a comment on the PR, disregard ;).
