### ISSUE TITLE
Keymaps are broken in the latest nightly for Pocketbooks

### ISSUE THREAD

**Issue by dmalinovsky** [koreader/koreader-base#1991]
[These changes](https://github.com/koreader/koreader-base/compare/24e97662dfd600437517463b6c49bad0aec4c6ad...25ba94b9c2d90fe5c4b15d53ce21d496afed8bf9) broke the keymapping support for Pocketbooks.

After upgrading to the latest nightly, my `event_map.lua` stopped having any effect:

```lua
return {
  [0x18] = "LPgFwd",
}
```

(This change simply maps both back and forward buttons to the PageForward action.)

After I downgraded to the latest release, 2024.11, keymap started working again.

**Comment by dmalinovsky** [comment]
I see, thank you. In this case, can someone please update https://github.com/koreader/koreader/wiki/Keymapping#pocketbook-devices?

**Comment by benoit-pierre** [comment]
> I see, thank you. In this case, can someone please update https://github.com/koreader/koreader/wiki/Keymapping#pocketbook-devices?

Done.
