### ISSUE TITLE
How to use in my app

### ISSUE THREAD

**Issue by LanmanGroup** [koreader/koreader-base#491]
how to include and use it in my app? Where can I find a sample? I need to create an app with inside a document viewer.

**Comment by houqp** [comment]
see https://github.com/koreader/koreader and https://github.com/koreader/kindlepdfviewer.

more specifically: https://github.com/koreader/koreader/blob/master/setupkoenv.lua and https://github.com/koreader/koreader/tree/master/frontend/apps
