### ISSUE TITLE
MuPDF 1.13

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader-base#656]
Pinging @TnS-hun :-)

It's not mentioned on https://mupdf.com/news.html yet but the `1.13.0` tag exists in the repo.

Because of the "Improvements to annotation editing API." mentioned in the changelog the build fails. I didn't investigate what changed exactly; this was just a quick test to see what would happen.

```
In file included from wrap-mupdf.c:24:0:
wrap-mupdf.h:119:21: error: unknown type name ‘fz_annot_type’; did you mean ‘fz_annot’?
     pdf_page *page, fz_annot_type type)
                     ^
wrap-mupdf.h:32:46: note: in definition of macro ‘MUPDF_WRAP’
     ret_type wrapper_name(fz_context *ctx, ##__VA_ARGS__);
                                              ^~~~~~~~~~~
In file included from wrap-mupdf.c:154:0:
wrap-mupdf.h:119:21: error: unknown type name ‘fz_annot_type’; did you mean ‘fz_annot’?
     pdf_page *page, fz_annot_type type)
                     ^
wrap-mupdf.h:49:53: note: in definition of macro ‘MUPDF_WRAP’
     extern ret_type wrapper_name(fz_context *ctx, ##__VA_ARGS__) { \
                                                     ^~~~~~~~~~~
```
![screenshot_2018-04-20_16-42-46](https://user-images.githubusercontent.com/202757/39057591-df7ad6d2-44b9-11e8-9c16-7bbf12f31666.png)

Edit: btw, [MuPDF Explored](https://ghostscript.com/%7Erobin/mupdf_explored.pdf) was updated too.

**Comment by TnS-hun** [comment]
Finally I had some time today to do this. :)
