### ISSUE TITLE
AppImage build fails

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader-base#730]
@NiLuJe I assume it's probably related to some of your recent changes. :-P

https://gitlab.com/koreader/nightly-builds/-/jobs/95161017
```
appimagetool: error while loading shared libraries: libcairo.so.2: cannot open shared object file: No such file or directory
```

**Comment by Frenzie** [comment]
PS I now manually added the both of us under Project → Settings → Integrations → Pipelines emails so these things shouldn't fly under the radar in the future anymore.

By default GitLab only tells you about pipelines you triggered yourself.

**Comment by NiLuJe** [comment]
Huh. Nothing we build should pull in Cairo :?

**Comment by NiLuJe** [comment]
That just looks like a missing runtime dep for AppImageKit in the build env
to me... Why it popped up just now while it's pretty much depended on Cairo
forever beats me, though.

**Comment by NiLuJe** [comment]
Well, not exactly "forever", but circa end of January 2017.

**Comment by Frenzie** [comment]
Oh you're right, I only glanced at it since I was focused on other things and didn't realize it was after the build process.

The simple fix might be to switch to the 1.0 release? I don't really feel like updating the Docker image for something simple like that atm, lol.

https://github.com/koreader/koreader/blob/2eabf1dfac0b95de7208308c0d71b22af8efb113/Makefile#L48

**Comment by NiLuJe** [comment]
To be perfectly fair, I did break AppImage recently ^^. But that was fixed in https://github.com/koreader/koreader-base/pull/722

(That was after having broken Ubuntu Touch & fixed it in https://github.com/koreader/koreader-base/pull/721 :D).

**Comment by Frenzie** [comment]
I just figured Cairo was a dep for MuPDF or something; I don't really know what the command-line AppImageKit tool would even need that for.

**Comment by NiLuJe** [comment]
Yeah, switching back to the latest release should do the job.

The culprit appears to be the libappimage related commits (https://github.com/AppImage/AppImageKit/commit/310bcd0ebc2833c1ac46b292021c636fce9ffd9d), because that appears to be where the [cairo dep](https://github.com/AppImage/libappimage/blob/master/cmake/dependencies.cmake#L13) comes from.

**Comment by NiLuJe** [comment]
Don't cross the streams! :D
