### ISSUE TITLE
Switch to busted v2.0.rc13-0

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader-base#905]
There are at least two pretty important fixes:
* https://github.com/Olivine-Labs/busted/commit/b5060dd6f154807c152ee64e9919258c1728a7f8 
* https://github.com/Olivine-Labs/busted/commit/db6d8b4be8fd099ab387efeb8232cfd905912abb This means we may be able to remove `--no-auto-insulate`. Cf. https://github.com/Olivine-Labs/busted/issues/496

https://github.com/Olivine-Labs/busted/compare/v2.0.rc12-1...v2.0.rc13-0

Should be problem-free.

**Comment by NiLuJe** [comment]
I've been using it since February without issue, FWIW.

Not that I run the testsuite often, but, still ;).

**Comment by NiLuJe** [comment]
An I was running master before that, anyway ;).

**Comment by Frenzie** [comment]
Yeah, I already tested it locally and I noticed no difference whatsoever. I'll update it today.
