### ISSUE TITLE
LPEG 1.0.2

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader-base#908]
@NiLuJe It doesn't seem to be in Gentoo yet. I suppose that'll be rectified soon enough?

http://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.0.2.tar.gz

The changelog isn't super informative:

```
HISTORY for LPeg 1.0.2

* Changes from version 1.0.1 to 1.0.2
  ---------------------------------
  + some bugs fixed

* Changes from version 0.12 to 1.0.1
  ---------------------------------
  + group "names" can be any Lua value
  + some bugs fixed
  + other small improvements
```

http://lua.2524044.n2.nabble.com/ANN-LPeg-1-0-2-td7685779.html

**Comment by NiLuJe** [comment]
Given the [latest commit](https://gitweb.gentoo.org/repo/gentoo.git/commit/dev-lua/lpeg?id=cec3d691c48b2c4255cb94403b6e8a5e6c0f0df0), I wouldn't get my hopes up :D.

**Comment by NiLuJe** [comment]
It'll probably be quicker to check if someone else is mirroring that somewhere ;).

**Comment by Frenzie** [comment]
Various other Linuxes, but for non-LTS type releases that may not be super stable.

Maybe FreeBSD?

```
http://distcache.FreeBSD.org/ports-distfiles/lpeg-1.0.2.tar.gz
```
